bash branch-copy-to-fork.sh "Wikipedia" "$1" "$2"
bash branch-copy-to-fork.sh "Wikibooks" "$1" "$2"
bash branch-copy-to-fork.sh "Wikidata" "$1" "$2"
bash branch-copy-to-fork.sh "Wikimedia Commons" "$1" "$2"
bash branch-copy-to-fork.sh "Wikinews" "$1" "$2"
bash branch-copy-to-fork.sh "Wikiquote" "$1" "$2"
bash branch-copy-to-fork.sh "Wikisource" "$1" "$2"
bash branch-copy-to-fork.sh "Wikispecies" "$1" "$2"
bash branch-copy-to-fork.sh "Wikiversity" "$1" "$2"
bash branch-copy-to-fork.sh "Wikivoyage" "$1" "$2"
bash branch-copy-to-fork.sh "Wiktionary" "$1" "$2"
bash branch-copy-to-fork.sh "Wikimedia" "$1" "$2"
